export const FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_REQUEST =
  "FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_REQUEST"
export const FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_SUCCESS =
  "FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_SUCCESS"
export const SELECT_CURRENCY_PAIR = "SELECT_CURRENCY_PAIR"
export const START_LOADING = "START_LOADING"
export const STOP_LOADING = "STOP_LOADING"
export const DEFAULT_TIMER_START_TIMEOUT = 1000
