export const FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_REQUEST =
  "FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_REQUEST"
export const FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_SUCCESS =
  "FETCH_CURRENCY_PAIRS_AND_EXCHANGE_RATES_SUCCESS"
export const FETCH_RATES_REQUEST = "FETCH_RATES_REQUEST"
export const FETCH_RATES_SUCCESS = "FETCH_RATES_SUCCESS"
export const FETCH_RATES_ERROR = "FETCH_RATES_ERROR"
